; FlowSense-X final PlatformIO configuration
; ESP32 DevKit V1 + Arduino

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    madhephaestus/ESP32Servo

build_flags =
    -DCORE_DEBUG_LEVEL=3
