#ifndef FLOWSENSE_MOTION_H
#define FLOWSENSE_MOTION_H

#include <Arduino.h>

// ==========================================================
// FlowSense-X
// S-Curve Motion Profile
// ==========================================================
//
// Target RPM
//     ↓
// S-Curve Profile
//     ↓
// Command RPM
//     ↓
// ESC
//
// Actual RPM is independently measured by
// the IR reflective sensor.
//
// ==========================================================

struct MotionState
{
    // Actual RPM measured by IR sensor
    float currentRpm;

    // User requested RPM
    float targetRpm;

    // RPM command generated by motion profile
    float commandRpm;

    // 0.0 -> 1.0 motion progress
    float normalizedPosition;

    // Motion currently active
    bool running;

    // Motion profile reached target
    bool complete;
};

// ==========================================================
// Initialization
// ==========================================================

void motionInit();

// ==========================================================
// Target
// ==========================================================

void motionSetTarget(
    float targetRpm
);

// ==========================================================
// Motion control
// ==========================================================

void motionStart();

void motionStop();

void motionUpdate(
    float dtSeconds
);

// ==========================================================
// Actual RPM feedback
// ==========================================================
//
// Supplied by IR reflective RPM sensor.
//
// ==========================================================

void motionSetMeasuredRpm(
    float measuredRpm
);

// ==========================================================
// State
// ==========================================================

MotionState motionGetState();

#endif // FLOWSENSE_MOTION_H