name: PlatformIO CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Build firmware
        run: pio run